# Generated by Django 2.0 on 2021-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30)),
                ('heroname', models.CharField(max_length=30)),
                ('heroinname', models.CharField(max_length=30)),
                ('directorname', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
