# Generated by Django 2.0 on 2021-06-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=90)),
                ('product_category', models.CharField(max_length=40)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
